version: '3'

services:

## PostgreSQL
## Banco para sonar
  db:
    container_name: postgresql
    restart: always
    image: postgres:13.2
    environment: 
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - ./devops/postgresql/postgresql_sonar:/var/lib/postgresql
      - ./devops/postgresql/postgresql_sonar_data:/var/lib/postgresql/data

## SonarQube
## login admin/sonar
  sonarqube:
    container_name: sonarqube
    image: sonarqube:8.6.1-community
    restart: always
    environment:
      - sonar.jdbc.url=jdbc:postgresql://db/sonar
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.search.javaAdditionalOpts=-Dbootstrap.system_call_filter=false
      - sonar.search.javaAdditionalOpts=-Dnode.store.allow_mmap=false
    ports:
      - 9000:9000
      - 9092:9092
    volumes:
      - ./devops/sonarqube/sonarqube_data:/opt/sonarqube/data
      - ./devops/sonarqube/sonarqube_logs:/opt/sonarqube/logs
      - ./devops/sonarqube/sonarqube_temp:/opt/sonarqube/temp
      - ./devops/sonarqube/sonarqube_extensions:/opt/sonarqube/extensions
    depends_on:
      - db
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

## Jenkins
  Jenkins:
    container_name: jenkins
    image: jenkins/jenkins:2.277.4-lts-jdk11
    restart: always
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./devops/jenkins/jenkins_home:/var/jenkins_home

## Tomcat
  tomcat:
    container_name: tomcat
    image: bitnami/tomcat:10.0.6
    restart: always
    ports:
      - 8888:8080
    environment:
      TOMCAT_USERNAME: tomcat
      TOMCAT_PASSWORD: tomcat
      TOMCAT_ALLOW_REMOTE_MANAGEMENT: 1
    depends_on:
      - mysqldb
    volumes:
      - ./devops/tomcat:/bitnami
      - ./devops/path/to/config/server.xml:/opt/bitnami/tomcat/conf/server.xml

## MySQL
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0.25
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .devops/mysql/data:/var/lib/mysql

## PhpMyAdmin
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:5.1.0
    restart: always
    ports:
      - 81:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysqldb